### ISSUE TITLE
Basic error

### ISSUE THREAD

**Issue by jagmohan-nanaware** [Adept196/adept#79]
Installed adept as suggested.

Getting error on running "python main.py". Can anyone help?

Here is the output
pygame 1.9.5.dev0
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from buffalo import utils
ImportError: No module named buffalo

**Comment by thomasdfischer** [comment]
@jagmohan-nanaware It looks like you don't have [buffalo](https://github.com/fschr/buffalo) installed. Try installing that and see if your error goes away.

On another note, this project is very old. It's typically best to encapsulate Python projects in their own environment. Historically, that has been achieved through [virtualenv](https://virtualenv.pypa.io/en/stable/). However, the Latest & Greatest™ solution to this problem might not be virtualenv --- I've been out of the Python loop for a couple years. Virtualenv should serve as a good starting point, nonetheless.

**Comment by jagmohan-nanaware** [comment]
Thanks Thomas.
